---
title: "p8105_hw1_yk2960"
author: "Youyuan(Keviant) Kong"
date: "2021/9/23"
output:
  github_document
#  word_document: default
#  html_document: default
#  pdf_document: default
---

```{r setup, include=FALSE}
#knitr::opts_chunk$set(echo = TRUE)
##library("tinytex")
##tinytex:: install_tinytex()
```
##Problem 1

```{r problem 1}
random_sample<-rnorm(10)
###a random sample of size 10 from a standard Normal distribution
logical_vector<-random_sample>0
##a logical vector indicating whether elements of the sample are greater than 0
char_vector<-rep("10",10)
##a character vector of length 10
factor_vector<-c("1","2","3","1","2","3","1","2","3","1")
factor_vector<-as.factor(factor_vector)
##a factor vector of length 10, with 3 different factor “levels”
dataFrame_problem1<-data.frame(random_sample,logical_vector,char_vector,factor_vector)
##take the mean of a variable in a dataframe
library(tidyverse)
mean(pull(dataFrame_problem1,1))
##numeric can get mean
mean(pull(dataFrame_problem1,2))
##logical can get mean
mean(pull(dataFrame_problem1,3))
mean(as.numeric(pull(dataFrame_problem1,3)))
##char cannot get mean
mean(pull(dataFrame_problem1,4))
mean(as.numeric(pull(dataFrame_problem1,4)))
##char cannot get mean
```


##Problem 2


```{r problem 2}
##install.packages("palmerpenguins")
library(palmerpenguins)
data("penguins", package = "palmerpenguins")
summary(penguins_raw)
str(penguins_raw)
nrow(penguins_raw)
ncol(penguins_raw)
complete_penguins_raw<-penguins_raw[complete.cases(penguins_raw$`Flipper Length (mm)`),]
mean(as.numeric(complete_penguins_raw$`Flipper Length (mm)`))
penguins_raw$`Culmen Length (mm)`
library(ggplot2)
plot<-ggplot(penguins_raw, aes(x=as.numeric(`Flipper Length (mm)`), y=as.numeric(`Culmen Length (mm)`),color=Species))+ geom_point(shape=1) 
plot
ggsave("Problem2 penguins' data plot.png",plot)
```

